sudo: false
language: node_js
node_js:
  - "10"
cache: yarn

jobs:
  include:
    - stage: test
      env:
        - NAME=yarn
      node_js: "10"
      before_script: yarn global add codecov
      script: yarn test
      after_success: codecov
    - stage: test
      env:
        - NAME=docker
      services: docker
      sudo: required
      script: docker build .
